Use proper rounding for controllers using imperial units
dustindclark/homebridge-rinnai-controlr pull request #20
Opened 2023-12-08 22:09 UTC by zimuliu

The controllers in US/Canada use steps like 98F/100F/102F/etc with 2F step size. This ensures the we properly set the temperature as set by customers in the HomeKit app.

This PR also fixed
*  the wrong defaults
* a wrong log output
* the rounding error on the temperature range

2023-12-12 14:09 UTC, zimuliu commented
@dustindclark can you review and merge? thanks!

2023-12-30 19:06 UTC, dustindclark requested changes

2023-12-30 19:06 UTC, dustindclark commented on config.schema.json
> +        "default": "98"
My Rinnai tankless minimum is 120 and max is 140. Can you point me to documentation where this is not the case? This is just a default and can be overridden.

2023-12-30 19:06 UTC, dustindclark commented on src/platformAccessory.ts
> +            .onGet(this.getTargetTemperature.bind(this))
Why are we renaming functions/variables to target temperature when we're setting the current temperature characteristic?

2023-12-30 19:06 UTC, dustindclark commented on src/constants.ts
> +export const WATER_HEATER_STEP_VALUE_IN_F = 2; // Controllers with the imperial unit, use 98/100/102/etc
I also don't have any problems setting my target temperature to odd numbers. We should either make this configurable instead of changing the default to step by 2s.

2024-05-16 03:07 UTC, zimuliu commented
Changes will be handled in https://github.com/dustindclark/homebridge-rinnai-controlr/pull/26

2024-05-16 03:07 UTC, closed without merging